module.exports.PaymentRouter = require('./payment.routes')
module.exports.OrderRouter = require('./order.routes')
module.exports.TshirtRouter = require('./tshirt.routes')
module.exports.UserRouter = require('./user.routes')
module.exports.DalleRouter = require('./dalle.routes')