module.exports.UserController = require('./user.controller')
module.exports.TshirtController = require('./tshirt.controller')
module.exports.PaymentController = require('./payment.controller')
module.exports.OrderController = require('./order.controller')
module.exports.DalleController = require('./dalle.controller')